fixtures:
  repositories:
    "archive": "git://github.com/voxpupuli/puppet-archive.git"
    "epel": "git://github.com/stahnma/puppet-module-epel.git"
    "staging": "git://github.com/voxpupuli/puppet-staging.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "systemd": "git://github.com/camptocamp/puppet-systemd.git"
  symlinks:
    "kong": "#{source_dir}"
